
DOTFILES=~/.config/dotfiles
ZSH_HOME="$DOTFILES/zsh_setup"

source "$ZSH_HOME/envs.sh"
source "$ZSH_HOME/utils.sh"
source "$ZSH_HOME/docs.sh"
source "$ZSH_HOME/hist.sh"
source "$ZSH_HOME/comp.sh"
source "$ZSH_HOME/theme.sh"
source "$ZSH_HOME/custom.sh"

echo '
 ____
< Hello! >
 ----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
'
